from abc import ABC, abstractmethod


class Sorting(ABC):

    @abstractmethod
    def sort(self, reverse: bool = False) -> None: ...
    @abstractmethod
    def items(self) -> list: ...
    @abstractmethod
    def generator(self) -> GeneratorExit: ...
    @abstractmethod
    def iterator(self) -> iter: ...
    @abstractmethod
    def printArray(self) -> None: ...
